# Generated by Django 4.1.4 on 2022-12-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('year_joined', models.CharField(max_length=4)),
            ],
        ),
    ]
